## Práctico Número 2: Implementando una red neuronal

### Tarea del dia
Hoy vamos a implementar entre todos, la red neuronal mas simple: la de una sola neurona. Tenemos las herramientas para hacerlo automaticamente con tensorflow, pero eso no seria divertido. El unico ayudante que tendremos es numpy.
Como vamos a implementar numpy, lo primero es ... importar numpy!! A esta altura deberia ser un acto reflejo ...

In [ ]:

# Sientete libre de importar esta libreria como mas te guste. Aqui te dejo unas opciones:
import numpy as np
# import numpy
# import numpy as npy
# import numpy as libreria_de_vectores
# Descomenta la que mas te guste o haz una nueva linea.

### Recordando el perceptron
Recordemos que es un perceptron. No introduzcamos palabras raras como sumatoria, ni funciones de activacion todavia. El perceptron es un *modelo*, que nos ayuda a *predecir* algo, a partir de *caracteristicas*.
Que son estas caracteristicas? Dicho de forma simple, es algo que la maquina puede entender, es decir numeros. Por ejemplo, pueden ser los numeros que describan a una persona: edad, peso, talla, etc.

![Perceptron simple](https://drive.google.com/uc?export=view&id=1QJqdjrwZR2iu9mdnsZXsGV6aDpoy9nOF)

En este caso, mis caracteristicas son n1 y n2, y eso nos va a ayudar a predecir *algo*.

#### Como lo hace?

Podemos empezar por un modelo muy muuy muuuy simple.

Primero supongamos que lo que queremos predecir es un valor tipo Verdadero o Falso, o un 1 o 0. Es decir, queremos predecir entre dos valores.

Sumamos las caracteristicas (que recuerden que no son mas que numeros). Si eso nos da arriba de un valor (llamemosle *umbral*), predecimos un 1 (o Verdadero), sino, predecimos un 0 (o Falso)


### Bajemoslo a tierra con un ejemplo

Queremos predecir si un alumno va a aprobar una materia o no, a partir de ciertas caracteristicas. Nuestras caracteristicas van a ser: resultado de examen 1, resultado de examen 2. Entre ambas, tienen que ser mayor a 12 para aprobar el curso.



![Perceptron complejo](https://drive.google.com/uc?export=view&id=1G83IAw0-tPuuMcBRp49GOnhprI2cvpXY)



No se asusten con ese simbolo raro, si no lo conocen, solo nos dice que sumamos el resultado del Examen1 + resultado del Examen 2


### Podremos implementar eso con codigo?
Primero lo primero, definamos nuestros datos, que van a ser super simples ...
Vamos a tener:
- alumno 1: saco 2 en el primer examen, y 9 en el segundo
- alumnos 2: saco 10 en el primer examen, y 9 en el segundo

In [ ]:
alumno_1 = [2,9]
alumno_2 = [10, 9]


Hasta ahora, tanto alumno_1 como alumno_2 son *listas*. Podemos juntar a ambas en un solo objeto

Hagamos eso

In [ ]:
alumnos = [alumno_1, alumno_2]
print(alumnos)

[[2, 9], [10, 9]]


La variable alumnos es ahora una *lista*, que a su vez esta compuesta de *listas* (es una lista de listas). Podemos pedirle a numpy que las transforme en una *matriz*. Esto es simplemente mas conveniente para la computadora. Le hagamos facil el trabajo. Esto lo podemos hacer con la *funcion* de numpy: numpy.array.

No se olviden que todo esto debe estar guardado en una variable

In [ ]:
alumnos_v = np.array(alumnos)
print(alumnos_v)

[[ 2  9]
 [10  9]]


In [ ]:
# Quiero que conozcas a los arrays de numpy. Hay un pequenio atributo de numpy que es "shape", que usaremos mas tarde. Puedes ver lo que hace?
print(alumnos_v.shape)
#el metodo shape de lista de numpy devuelve el tamaño de la matriz
print(f"{alumnos_v.shape[0]} es el numero de alumnos")
print(f"{alumnos_v.shape[1]} es el numero de examanes por alumno")

(2, 2)
2 es el numero de alumnos
2 es el numero de examanes por alumno


In [ ]:
# Como me entero de cuanto saco el primer alumno en el segundo examen, por ejemplo?
# Veamoslo en codigo:

print(f"El primer alumno saco {alumnos_v[0,1]} en el segundo examen")
print(f"El segundo alumno saco {alumnos_v[1,1]} en el segundo examen")

# En general, en matrices de numpy, el primer numero de lo que hay entre corchetes hace referencia a la fila, (que en este caso son los alumnos), y el segundo numero a la columna
# que en este caso son los examenes
# Acuerdense que python empieza a contar desde el 0 (le fue mal en el jardin de infantes, pobre)

El primer alumno saco 9 en el segundo examen
El segundo alumno saco 9 en el segundo examen


Tenemos nuestra base de datos!
Ahora armemos nuestro perceptron!
Para los mas avanzados, intenten hacer una *clase* perceptron, para el resto, esta bien una *funcion*. Esta *funcion* tomara los datos y simplemente devolvera la suma de ellos.
Puedes hacer esto?

Hay una forma facil y un poco ... incorrecta de hacerlo. Mas que incorrecta es mas lenta, pero nos conformaremos con eso por ahora. Solo quiero que sepas que existe una forma mejor de hacer lo mismo. Si sabes cual es la forma rapida, implementala. Si no, puedes hacer la suma mediante loops for.

In [ ]:
print(alumnos_v)

[[ 2  9]
 [10  9]]


In [ ]:
[11, 19]

[11, 19]

In [ ]:
def perceptron(datos):
    # definimos una lista vacia, primero. En nuestro caso, al final esta contendra nuestra lista de aprobados y desaprobados

    respuesta = [] #------------completar-------
    # en este caso, "dato" sera alumno, pero dependera de que se le pase como parametro
    for dato in datos:
        print(f"dato es {dato}")
        sumatoria = 0
        # definimos una sumatoria = 0, y le iremos sumando el valor de cada uno de los features.

        # sumatoria = #-----------completar-------------
        # en nuestro caso, "feature" puede tomar el valor: examen_1 o examen_2
        for feature in dato:
            sumatoria = sumatoria + feature
        print(f"sumatoria es {sumatoria}")
        respuesta.append(sumatoria)
        # recuerden que en machine learning, trabajamos con numpy arrays!
    respuesta_v = np.array(respuesta)


    return respuesta_v


Bien, ya definimos nuestro perceptron, pero por ahora solamente lo definimos. Ahora tenemos que *llamar* a esa funcion con nuestros datos.

In [ ]:
y = perceptron(alumnos_v)
print(y)

dato es [2 9]
sumatoria es 11
dato es [10  9]
sumatoria es 19
[11 19]


Ok, esto nos tira dos numeros, pero no quiero una lista de numeros de 0 a 20, quiero lista de aprobados y desaprobados. Al perceptron le falta algo, que llamaremos la *funcion de activacion*. La *funcion de activacion* es algo que procesa la suma que hicimos dentro del perceptron y lo transforma en otro numero, segun ciertas *reglas*.

Hay diferentes *funciones de activacion*, pero recuerden que ahora solo queremos saber si el alumno suma mas de 12 entre sus dos examenes o no. Entonces nuestra funcion de activacion devolvera un uno si la suma es mayor que 12 (que interpretaremos como *aprobado*), y un 0 si es menos que 12 (que interpretaremos como *desaprobado*). Esta *funcion de activacion* es llamada ***funcion escalon***.

Ahora, la funcion de activacion es parte del perceptron, asi que la definiremos primero, y luego haremos que la *funcion* que definimos previamente, es decir la funcion *perceptron* ***llame*** a la *funcion* *escalon*.

In [ ]:
def funcion_escalon(sumatoria, umbral):
    salida = []
    for rtta in sumatoria:
        if rtta >= umbral:  #-------completar---------:
            salida.append(1)
        else:
            salida.append(0)

    # transformamos nuestra salida, porque en machine learning trabajamos con numpy arrays
    salida = np.array(salida)
    return salida

Redefinimos nuestra funcion de perceptron

In [ ]:
def perceptron(datos, umbral):
    # definimos una lista vacia, primero. En nuestro caso, al final esta contendra nuestra lista de aprobados y desaprobados

    respuesta = [] #-------completar--------
    # en este caso, "dato" sera alumno, pero dependera de que se le pase como parametro
    for dato in datos:
        # definimos una sumatoria = 0, y le iremos sumando el valor de cada uno de los features.
        sumatoria = 0 #-------completar---------
        # en nuestro caso, "feature" puede tomar el valor: examen_1 o examen_2
        for feature in dato:
            sumatoria += feature #-------completar--------
        respuesta.append(sumatoria)
        # recuerden que en machine learning, trabajamos con numpy arrays!
        respuesta_v = np.array(respuesta)

    # Ahora llamamos al final a nuestra funcion escalon
    respuesta_final = funcion_escalon(respuesta_v,  umbral)    #---completar-------)


    return respuesta_final

In [ ]:
aprobados_desaprobados = perceptron(alumnos_v, 12)
print(f"Estos son nuestros aprobados y desaprobados: {aprobados_desaprobados}")


Estos son nuestros aprobados y desaprobados: [0 1]


Creanlo o no, acaban de implementar su primer perceptron. Todavia le faltan un par de cosas para que sea completamente funcional y poder incorporarlo a un red neuronal como la gente. Pero esta pequenia funcion ya es un perceptron (o neurona)

#### Completando el panorama
Que pasa si el examen 2 es mas clave o importante que el examen 1, o al reves? Por que estaria obligado a que valgan lo mismo? Supongamos que el examen 2 cubre mas temas, y que quiero que valga mas. Para eso, vamos a implementar unos *pesos*. Esto quiere decir que simplemente vamos a estar multiplicando cada caracteristica por un numero. Digamos que queremos que el Examen 2 valga el 50% mas que el examen 1. Para eso, podemos multiplicar al examen 1 por 1, y al examen 2 por 1.5.  
Pueden modificar la funcion para que haga eso?

In [ ]:
# Primero, definimos nuestros pesos.
w = [1,1.5]
print(w)

[1, 1.5]


In [ ]:
# Pero en machine learning con que trabajamos? Todos juntos: numpy array!
w = np.array(w)
print(w)
print("Noten que a proposito puse los pesos en w en el mismo orden que los features.\n \
    Esto nos servira en la proxima funcion")

[1.  1.5]
Noten que a proposito puse los pesos en w en el mismo orden que los features.
     Esto nos servira en la proxima funcion


In [ ]:
# Ahora modifiquemos la funcion anterior (copien y peguen, y le ponemos un nuevo nombre, no le digan a nadie ...)
def perceptron_w(datos, w, umbral):
    respuesta = [] #-------completar-------
    #sumatoria = #------completar---------

    # en el proximo loop for es donde esta la diferencia clave.
    # Podemos usar la palabra clave "range", para acceder a ambas listas por orden
    for i in range(0,datos.shape[0]): # i correspondera al alumno
        sumatoria = 0
        for j in range(0, datos.shape[1]): # j correspondera al examen

            if j==1:
              sumatoria = sumatoria + (datos[i,j] * w[1])
            #sumatoria += #---------completar con el producto del peso por el elemento del examen

        respuesta.append(sumatoria)
    respuesta_v = np.array(respuesta)
    respuesta_final = funcion_escalon(respuesta_v, umbral) #completar-----)
    return respuesta_final

In [ ]:
aprobados_desaprobados = perceptron_w(alumnos_v, w, 12)
print(f"La lista de aprobados y desaprobados es {aprobados_desaprobados}")
print(f"Gracias a los pesos, todos aprobaron! ")

0
1
La lista de aprobados y desaprobados es [1 1]
Gracias a los pesos, todos aprobaron! 


#### Facturas
creo que a ese perceptron le falta algo. Esos alumnos le llevaron facturas al profesor? Llevarle facturas al profesor es muy importante. Nadie puede aprobar sin llevarle facturas al profesor. Por lo tanto, necesitaremos ***otro*** perceptron para manejar este dato de la manera mas adecuada.
![Perceptron con facturas](https://drive.google.com/uc?export=view&id=1aIiyftevn4rLvp_kqU512JOzpVQgc8Cx)


In [ ]:
class Perceptron:
  #builders
  def __init__(self, datos, pesos, umbral) -> None:
    self.__alumnos = np.array(datos)
    self.__w = np.array(pesos)
    self.__umbral = umbral
    print(f"Alumnos: ")
    print(self.__alumnos)
    print(f"Pesos: {self.__w}")
    print(f"Umbral: {umbral}")
    #con np.array transformamos a matriz

  def __funcion_escalon(self, sumatoria, umbral) -> list:
    salida = []
    for rtta in sumatoria:
      if rtta >= umbral:
        salida.append(1)
      else:
        salida.append(0)
    return salida

  def perceptron_w(self) -> list:
    print()
    respuesta = []

    for i in range(0, self.__alumnos.shape[0]):
      sumatoria = 0
      for j in range(0, self.__alumnos.shape[1]):
        if j != 2: ##Aca controlamos que no sume la columna de facturas, ya que es un control
          if (j==1):
            #preguntamos por la columna ya que el examen_2 es el que tiene mayor peso
            sumatoria += (self.__alumnos[i, j] * self.__w[1])
          else:
            sumatoria += (self.__alumnos[i, j] * self.__w[0])
      print(f"Nota del alumno {i} es igual a -> {sumatoria}")
      respuesta.append(sumatoria)
    respuesta_v = np.array(respuesta)
    respuesta_final = self.__funcion_escalon(respuesta_v, self.__umbral)

    return respuesta_final

  def perceptron_f(self) -> list: #Perceptron que controla si trajeron facturas
    print()
    respuesta = []
    for a in range(0,self.__alumnos.shape[0]):
      if self.__trajoFacturas(self.__alumnos[a]):
        print(f"El alumno {a} aprobo! Trajo Facturas")
        respuesta.append(1)
      else:
        print(f"El alumno {a} desaprobo! No Trajo Facturas")
        respuesta.append(0)
    respuesta_final = np.array(respuesta)
    return respuesta_final

  #Metodo privado que me devuelve un boolean
  def __trajoFacturas(self, alumno) -> bool:
    flag = False
    #Le tenemos que pasar a este metodo esa fila,osea una lista
    for i in range(0, len(alumno)):
      if i==2 and alumno[i]==1:
        flag = True

    return flag


if (__name__ == '__main__'):
  #Ahora queremos testear si los alumnos trajeron factura ya que en esos se basaran si aprobaron o no
  alumno_1 = [2, 9, 1]
  alumno_2 = [10, 9, 0]
  alumno_3 = [3, 2, 1]  #Con la tercera columna testearemos con 1 si trajo factura o con 0 si no trajo
  alumnos = [alumno_1, alumno_2, alumno_3]

  pesos = [1, 1.5]
  clsPerc = Perceptron(alumnos, pesos, 12)
  print(f"La lista de aprobados y desaprobados es {clsPerc.perceptron_w()}")

  print(f"La lista de aprobados y desaporbados por traer facturas {clsPerc.perceptron_f()}")

Alumnos: 
[[ 2  9  1]
 [10  9  0]
 [ 3  2  1]]
Pesos: [1.  1.5]
Umbral: 12

Nota del alumno 0 es igual a -> 15.5
Nota del alumno 1 es igual a -> 23.5
Nota del alumno 2 es igual a -> 6.0
La lista de aprobados y desaprobados es [1, 1, 0]

El alumno 0 aprobo! Trajo Facturas
El alumno 1 desaprobo! No Trajo Facturas
El alumno 2 aprobo! Trajo Facturas
La lista de aprobados y desaporbados por traer facturas [1 0 1]
